paperclip-rs/paperclip

.travis.yml, Makefile
=> [#20] Switch to checking generated crates

src/v2/codegen/state.rs, tests/test_k8s.rs
=> [#29] Support request timeouts in generated CLI

core/src/v2/actix.rs, core/src/v2/models.rs
Fixes #109
Please review and let me know if i need to update any of the data types - After reading into the data types required, I used `u32` for the `integer` values and `f32` for the `number` values.
=> Parameter object

core/src/v2/models.rs
Hopefully I understood correctly what was needed.
=> #108 added missing fields to items object

book/build-script.md, book/cli.md
Update the link in the CLI example with a valid link for #123
cc/ @wafflespeanut
=> Update link in CLI example

src/bin/main.rs
update crate name and version from CLI args #130
=> Update Cratemeta values from CLI values

core/src/v2/mod.rs, core/src/v2/models.rs, src/v2/codegen/emitter.rs, src/v2/codegen/state.rs, tests/pet-v2.yaml, tests/test_app.rs, tests/test_emitter.rs
fixes #34 
Here's what I came up with. Would appreciate any pointers to code/tests
=> [#34] Add info field

Cargo.toml, core/Cargo.toml, core/src/v2/schema.rs
I've found this feature useful for me - works perfect with actix plugin.
=> Decimal field type (as a feature)

book/actix-plugin.md, core/src/v2/actix.rs, core/src/v2/models.rs, core/src/v2/schema.rs, macros/src/actix.rs, macros/src/lib.rs, plugins/actix-web/src/lib.rs, src/lib.rs, tests/test_app.rs
- Added api_v2_security macro for actix plugin
=> Security definitions

Cargo.toml, core/Cargo.toml, core/src/v2/actix.rs, core/src/v2/schema.rs
I'm not sure if these types covers all possible multipart cases, but better this than nothing :-)
=> Impl OperationModifier for actix_multipart

plugins/actix-web/Cargo.toml
(kudos for using that version range 👀)
=> do not include default features for actix-web

core/src/v2/schema.rs, tests/test_app.rs
The types `chrono::{DateTime, NaiveDateTime}` were already supported, this adds `chrono::{Date, NaiveDate}`
=> Add chrono Date types

CHANGELOG.md, Cargo.toml, core/Cargo.toml, core/src/v2/actix.rs, core/src/v2/schema.rs
=> Add actix-session support

.travis.yml, Makefile, core/src/util.rs, core/src/v2/actix.rs, core/src/v2/extensions.rs, core/src/v2/mod.rs, core/src/v2/models.rs, core/src/v2/resolver.rs, core/src/v2/schema.rs, macros/src/actix.rs, macros/src/core.rs, plugins/actix-web/src/lib.rs, plugins/actix-web/src/web.rs, rustfmt.toml, src/bin/main.rs, src/build/build.rs, src/error.rs, src/lib.rs, src/v2/codegen/author.rs, src/v2/codegen/emitter.rs, src/v2/codegen/impls.rs, src/v2/codegen/mod.rs, src/v2/codegen/object.rs, src/v2/codegen/state.rs, src/v2/mod.rs, tests/test_app.rs, tests/test_codegen.rs
Apply some code styling and add them to the Makefile for the future!
Includes also some tiny logical changes. I'll highlight them with comments.
This change is so opinionated, feel free to comment or reject :D
=> Some code styling, thanks to nightly fmt and clippy

.github/workflows/linter.yml, core/src/v2/models.rs, macros/src/actix.rs, plugins/actix-web/src/web.rs, src/build/build.rs
Currently both clippy and rustfmt are running
on nightly. Also the corresponding suggestions recommended
by clippy has been applied
~( Probably should wait for a rebase after https://github.com/paperclip-rs/paperclip/pull/339 is merged )~
=> ci: added linters 

.github/workflows/linter.yml, CHANGELOG.md, macros/src/actix.rs, tests/test_app.rs
Skips fields if the serde skip attribute is found.
Closes #305
=> feat(skip): add support for serde skip

book/actix-plugin.md
Paperclip version 0.4 is not compatible with Actix 3, only version 0.5 works
=> Update paperclip version

.github/workflows/cicd.yml
=> chore: update cicd to include v3 feature test

Cargo.toml, plugins/actix-web/Cargo.toml, plugins/actix-web/src/lib.rs, plugins/actix-web/swagger-ui
=> chore: release 0.4.2 of the paperclip-actix plugin

Cargo.toml, core/Cargo.toml, core/src/v3/openapi.rs, core/src/v3/operation.rs, core/src/v3/parameter.rs, core/src/v3/paths.rs, core/src/v3/request_body.rs, core/src/v3/response.rs, core/src/v3/schema.rs, core/src/v3/security_scheme.rs, plugins/actix-web/Cargo.toml
I'm getting the https://github.com/glademiller/openapiv3 crate ready for a 1.0.0 release. To that end, I wanted to make sure consumers were ok with the changes. As one of the more popular consumers, would you be amenable to taking a look? If you're happy enough with it, I'll do some final checks and publish 1.0.0 in the next couple of weeks.
=> updates for openapiv3 1.0.0

CHANGELOG.md, core/src/v2/models.rs, core/src/v2/schema.rs, tests/test_app.rs
It becomes a generic ip..
Resolves: #381
=> chore: add IpAddr as string format ip

plugins/actix-web/src/web.rs, plugins/actix-web/src/web3.rs, tests/test_app.rs
So instead of inserting an item and overwriting the existing I simply append the existing maps.
Should fix #380
=> fix: Append scope services instead of replacing

CHANGELOG.md, Cargo.toml, plugins/actix-web/src/app.rs, plugins/actix-web/src/web.rs, tests/test_app.rs
This should fix issue #404 by properly supporting non-BoxBody response payload types.
=> Fix issue #404

core/src/v2/models.rs, plugins/actix-web/src/app3.rs
This PR should silence some clippy warnings on master
=> Fix some clippy warnings

plugins/actix-web/src/web.rs, tests/test_app.rs
This PR makes paperclip's scope compatible with middlewares that don't return a box body. See the issue I opened here.
https://github.com/paperclip-rs/paperclip/issues/456.
Changes
1. Add an extra type parameter `B` with the same constraints as `actix_web::Scope` to the wrap function on paperclip's `Scope`
2. Remove the `Response = ServiceResponse` constraint on the impl block of `Scope<actix_web<Scope<T>>>`
3. Updated the `Response = ServiceResponse` constraint on route to `Response = <<actix_web::Route as ServiceFactory<ServiceRequest>>::Service as actix_service::Service<ServiceRequest,>>::Response`, AKA the response type of route as specified by actix-web. This happens to be `ServiceResponse` as of 4.1.0 so not an actual change but it does remove a place paperclip is hard-coding the …
=> fix: support non-boxed bodies in scope middleware

plugins/actix-web/src/app.rs, plugins/actix-web/src/app3.rs, tests/test_app.rs
Remove extra slash and fix test usage..
Resolves: #459
=> fix(rapidoc): remove extra slash

Cargo.toml, core/Cargo.toml, core/src/v2/actix.rs, core/src/v2/schema.rs, tests/test_app.rs
Add a way to specify uuid 0 or 1, or both!
=> feat: add uuid0 and uuid1 features

shell.nix, src/build/build.rs, src/v2/codegen/state.rs
=> chore: fix nightly linter

macros/src/actix.rs
=> style: add clippy exception for api_v2_operation struct

.github/workflows/linter.yml, shell.nix, src/v2/codegen/emitter.rs, src/v2/codegen/impls.rs, tests/test_app.rs
=> style: fix nightly lints

Cargo.toml, core/Cargo.toml, plugins/actix-web/Cargo.toml
=> chore: update openapiv3 crate

macros/src/lib.rs, plugins/actix-web/src/lib.rs, src/lib.rs
=> Support for HEAD

core/src/v2/schema.rs, tests/test_app.rs
=> feat: Add support for PathBuf type

macros/src/actix.rs
=> fix(useless vec): clippy + performance fix

core/src/v2/models.rs, core/src/v3/info.rs, tests/test_app.rs
Adds missing tos from openapi info.
Resolves: #520
=> fix: add missing tos

core/src/v2/schema.rs, macros/src/core.rs, tests/test_app.rs
=> feat: add max/min for 8, 16 and 128 bit integers
