paperclip-rs/paperclip

openapi/src/v2/codegen/mod.rs

fix #8 
I added rust strict keywords following https://doc.rust-lang.org/reference/keywords.html

Add all strict keywords #8

---

macros/src/actix/mod.rs

If one uses the return keyword in a handler returning the generic `impl Responder` or `Future`, the code generated by the procedural macro falls apart, because the return bypasses the wrapper.
```rust
#[api_v2_operation]
fn test(body: web::Json<InputStruct>) -> impl Responder {
if check_input(&body) {
return HttpResponse::BadRequest();
};
do_work();
HttpResponse::Ok()
}
```
The correct way to go about this would probably be to find every return statement and wrap it individually as well, but wrapping the block in a lambda makes it hygienic enough that returns work.
This change shouldn't break anything i think.

Fix return in generic impl Handlers

---

Cargo.toml
Makefile
core/Cargo.toml
core/src/v2/schema.rs
tests/test_app.rs

This PR Resolves #106 
- Adds `uuid = 0` (with `optional = true`) in Cargo.toml of core crate.
- Adds `uuid` with `serde` enabled  in Cargo.toml of root crate.
- Add a new feature named `uid` = `[uuid]` to Cargo.toml core crate & `uid = ["paperclip-core/uid"]` in root Cargo.toml
- Add an implementation for `uuid::Uuid` format
- Updates tests

[#106] Support uuid format with feature flag

---

src/v2/codegen/emitter.rs

This pull request fixes #105. 
Although this does exactly what was explained in the issue, I am a bit skeptical about passing mutable `Vec<CollectionFormat>`.
In case you'd want to suggest any changes in the approach, please let me know.

fixes #105

---

book/build-script.md

I have fixed the broken links in the build-script.md file. Cheers.
Fixes  #120

Fix broken 'addPet' and 'id and name fields' links

---

macros/src/actix/mod.rs
tests/test_app.rs

Resolves #76 
- Add support for `newtype` or `1 tuple structs`
- Extract getting the field type logic to a new `fn get_field_type`

[#76] Support newtype

---

core/src/v2/models.rs
src/v2/codegen/emitter.rs
src/v2/codegen/impls.rs
src/v2/codegen/object.rs
tests/pet-v2.yaml
tests/test_codegen.rs

This PR Resolves #35 
-  Adds `deprecated` field to `Operation`, `OpRequirement`
-  Adds generation of `[#deprecated]` attribute in builder, if 'deprecation` value present

[#35] Use deprecated field for operations

---

core/src/v2/schema.rs

To fix compilation errors on the latest nightly.

fix compilation errors: copy impl from trait and mark default

---

Cargo.toml
core/Cargo.toml
core/src/v2/actix.rs
core/src/v2/mod.rs
core/src/v2/schema.rs
macros/src/actix/mod.rs
plugins/actix-web/Cargo.toml
plugins/actix-web/src/lib.rs
plugins/actix-web/src/web.rs
src/lib.rs
tests/test_app.rs

I've updated versions of all actix libs and futures lib.
It worked for one of my project but I'm not sure if I've done all this properly. I'll have to do more testing (two another projects awaits), but I'm creating this PR as a draft so someone else can take a look at it to maybe spot something.
As far as i noticed this won't compile with actix-web openssl feature (happily it works with rustls)
Also I couldn't manage to wrap async/await handler with api_v2_operation macro, I'll investigate it shortly.

Updated actix-web to 2.0, updated futures to 0.3

---

book/actix-plugin.md
core/src/v2/actix.rs
core/src/v2/schema.rs
macros/Cargo.toml
macros/src/actix/mod.rs
macros/src/lib.rs
plugins/actix-web/src/lib.rs
src/lib.rs
tests/test_app.rs

I've added api_v2_errors macro which implements Apiv2Errors trait for selected struct - it can be then (afer implementing also ResponseError) used in handler return type (example added in tests) to document errors in swagger.
Additional implementation of OperationModifier on Result<T, E> where
T is OperationModifier and E is OprationErrorsModifier
allows to automatically add defined errocodes to swagger handler response.
I'll test it in my project if it will work smooth in following days, but meanwhile you could maybe take a look if this approach is good enough (it's not the best for sure :-))

Added api_v2_errors

---

Cargo.toml
src/v2/codegen/impls.rs
src/v2/codegen/object.rs

Without these changes, `paperclip` won't compile if any crate in the dep tree uses that feature. I made sure that the `kv_unstable` dependency is not part of `paperclip`, but only of the `dev-dependencies`, so we'll see the failure with `cargo test`, but not expose the feature to users of `paperclip`.

Harden `paperclip` against other crates using the `kv_unstable` feature of `log`

---

macros/src/actix.rs
macros/src/lib.rs
plugins/actix-web/src/lib.rs
src/lib.rs
tests/test_app.rs

The input was never modified, so it seemed better to make it a derive macro. The major change compared to master is is that you need to specify `#[openapi(empty)]` in addition to `#[derive(Apiv2Schema)]` if you want an `Any` type

Use a derive proc macro instead of an attribute proc macro

---

core/src/v2/schema.rs
macros/src/actix.rs
macros/src/lib.rs
plugins/actix-web/src/lib.rs
src/bin/main.rs
src/lib.rs
tests/test_app.rs

Based on #169
Causes any documentation on `#[derive(Apiv2Schema)]` types to get exposed as an OpenApi `description` field.

Forward user docs

---

Cargo.toml
book/build-script.md
core/Cargo.toml
core/src/error.rs
src/bin/main.rs
src/build/cli_main.hbs
src/build/client_mod.hbs
src/build/manifest.hbs
src/error.rs
src/lib.rs
src/v2/codegen/author.rs
src/v2/codegen/emitter.rs
src/v2/codegen/state.rs
tests/test_codegen.rs
tests/test_k8s.rs
tests/test_k8s/Cargo.toml
tests/test_k8s/lib.rs

`failure` is deprecated, and `thiserror` + `anyhow` combination is the most similar migration target.

Migrate from failure

---

.travis.yml

I sorted them by duration. 
Because Travis launches them sequentially in declaration order, this will optimize total wait time when not all workers are available.

Reorder CI jobs

---

macros/src/actix.rs

This should fix the broken build.
I was trying to figure out how this ever worked, and why it suddenly broke. Looks like `proc-macro-error` introduced a "breaking" (IMO this never should have worked) change from 1.0.2 to 1.0.3, as everything is green if you pin `proc-macro-error` to `=1.0.2`. I'm an absolute novice here, but [this jumped out](https://gitlab.com/CreepySkeleton/proc-macro-error/-/commit/141ebd775d63ada98d9f17eca8762d6c3522d55e).

Fix a mis-namespaced TokenStream ref

---

book/actix-plugin.md

According to the book, `actix` and `nightly` features should be used, but as far as I can [see](https://github.com/wafflespeanut/paperclip/blob/master/Cargo.toml#L58), `actix-nightly` should be used instead.

Fix actix-web features documentation

---

core/src/v2/schema.rs
tests/test_app.rs

Now, when serde_json::Value or serde_yaaml::Value is used in schema, it doesn't have type present in specs which makes it invisible in swagger web interface.
This PR makes it seen as "object", thus visible in swagger web interface as "{}".

Impl schema for serde values as "other"

---

Cargo.toml
core/Cargo.toml
plugins/actix-web/Cargo.toml

This needs so Cargo can deduplicate some of the dependencies when used with other packages in the project.
Paperclip seems to be working just fine with these even though the versions have some breaking changes.

refactor: Extended the support to wider range of versions of some dependencies

---

core/src/v2/models.rs
plugins/actix-web/Cargo.toml
plugins/actix-web/src/lib.rs
tests/test_app.rs

This PR fixes issue and one nit related to shared parameters generation:
- body is usually unique per method, hence do not generalize on body (e.g. patch has all fields optional)
- do not generalize when path has single method. also this generalized parameters feature nevertheless is part of a spec having some issues with some renderers, like redoc.

Fix shared parameters generation

---

Cargo.toml
core/src/v2/schema.rs
tests/test_app.rs

As provided in a test case
```
#[derive(Serialize, Apiv2Schema)]
struct Catalogue {
pub folders: HashMap<Uuid, Vec<Image>>
}
```
produces error:
```
--> tests/test_app.rs:841:25
|
841 |     #[derive(Serialize, Apiv2Schema)]
|                         ^^^^^^^^^^^ function or associated item not found in `std::collections::HashMap<uuid::Uuid, std::vec::Vec<test_map_in_out::Image>>`
|
= note: the method `raw_schema` exists but the following trait bounds were not satisfied:
`&std::collections::HashMap<uuid::Uuid, std::vec::Vec<test_map_in_out::Image>>: paperclip_core::v2::schema::TypedData`
which is required by `&std::collections::HashMap<uuid::Uuid, std::vec::Vec<test_map_in_out::Image>>: paperclip_core::v2::schema::Apiv2Schema`
...
```
This is caused by that HashMap implements Apiv2Schema …

Fix: derive Apiv2Schema on struct using HashMap<Uuid, String>

---

macros/Cargo.toml
macros/src/actix.rs
tests/test_app.rs

Some Operation parameters might be initialized via macro attributes, I believe this was discussed prior.
This change adds parsing of api_v2_operation macro attributes, it will validate if attribute can be initialized via macro parameter it will add that initialization to the operation init code.
Supported set of attributes:
- summary
- description
- operation_id
- consumes
- produces
If summary attribute is empty it will try to obtain summary and description from a function doc comments.

Initialize Operation parameters via macro attributes

---

Cargo.toml
core/Cargo.toml
plugins/actix-web/Cargo.toml

Actix 3.0 has been recently released. It seems that paperclip (v0.4.1)
builds just fine against both actix-web 2.0 and 3.0
(and their dependent libs).
So just relax the dependency and let downstream crates choose which major
version of actix they pull.
I've tested this with downstream crates requiring both actix 2.0 and crates requiring 3.0,
works wel. YMMV.
This change is based (in git sense) on v0.4.1 tag rather than current master. Current master seems to contain feature changes to be released as v0.5. It would be cool if actix 3.0 support can be released earlier as v0.4.2 (v0.2.2). If you'd create a branch out of v0.4.1 (or a some later commit still slated for "stable" 0.4 branch), I'll change target of this PR and it should apply cleanly.

Deps: allow also actix-web 3.0 in addition to 2.0 (for v0.4.*)

---

core/src/v2/schema.rs
tests/test_app.rs

I'm not sure if this is more correct, but it feels more correct to me. Out of all of the variants of `serde_json::Value` only one of them is an `object`.
Closes #235

Remove object type from json and yaml Values

---

core/src/v2/schema.rs

Currently it is not possible to generate schema name for container types, except the wrapped type `T::NAME`. But there might be different wrappers for various purposes. For instance we have wrapper for paginated results and since Rust does not support concatenation of const str I am not able to assign NAME to custom Apiv2Schema impl:
```
impl<T: Apiv2Schema> Apiv2Schema for Paginated<T> {
const NAME: Option<&'static str> = None;
fn raw_schema() -> DefaultSchemaRaw {
let mut schema = DefaultSchemaRaw::default();
schema.name = Some(format!("Paginated{}", T::NAME.unwrap_or("Unknown")));
schema.description = Some(format!("Paginated results.\n<br/>Item description: {}", T::DESCRIPTION));
{
let s = Vec::<T>::raw_schema();
schema.properties.insert("data".into(), s.into());
}
{
let mut s = …
```

Allow schema binding by dynamically generated name

---

Cargo.toml
macros/src/actix.rs
tests/test_app.rs

This change adds support for #[serde(flatten)] item attribute for Apiv2Schema derive macro. This allows to reuse structs for building flat JSON queries and responses like in example below:
```
#[derive(Deserialize, Serialize, Apiv2Schema)]
struct Paging {
/// Starting image number
offset: i32,
/// Total images found
total: i32,
/// Page size
size: i32,
};
#[derive(Serialize, Apiv2Schema)]
struct Image {
data: String,
id: Uuid,
time: chrono_dev::DateTime<chrono_dev::Utc>,
}
/// Images response with paging information embedded
#[derive(Serialize, Apiv2Schema)]
struct Images {
data: Vec<Image>,
#[serde(flatten)]
paging: Paging,
}
```
will turn into
```
"Images": {
"properties": {
"data": {
"items": {
"properties": {
"data": {
"type": "string"
},
"id": {
"format": "uuid",
"type": "string"
}, …
```

Adds support for serde(flatten)

---

book/actix-plugin.md
core/src/v2/actix.rs
core/src/v2/mod.rs
src/lib.rs
tests/test_app.rs

Add types to encode successful response codes in actix-web:
* `NoContent`
* `AcceptedJson`
* `CreatedJson`
Allows status codes to be used both by paperclip and actix-web, eg.
```rust
use paperclip::actix::web::Json;
use paperclip::actix::{CreatedJson, AcceptedJson, NoContent};
// 201 Created 
#[api_v2_operation]
async fn adopt_pet(body: Json<Pet>) -> Result<CreatedJson<Pet>, ()> {
let pet: Pet = body.into_inner();
// bring the pet home
Ok(CreatedJson(pet))
}
// 204 No Content
#[api_v2_operation]
async fn acknowledge_pet(body: Json<Pet>) -> NoContent {
NoContent
}
```
I was not really sure where to put this, I put it in `paperclip_core::v2::actix` because it fit there the easiest.
#62 #241

Add types for encoding successful response codes

---

CHANGELOG.md
book/actix-plugin.md
core/src/v2/models.rs
macros/Cargo.toml
macros/src/actix.rs
plugins/actix-web/src/lib.rs
tests/test_app.rs

Built on top of #217 this change allows to configure list of tags, info and other Api specification defaults when using actix plugin. I believe this closes the loop to be able to build a nice looking spec, e.g. allowing to render APIs grouped by categories:
To configure default I initially thought to add methods to App, but it is safer to configure defaults right when Api wrapper is created. Hence I've extended trait with additional method. This should provide full back compatibility.:
```
let mut spec = DefaultApiRaw::default();
spec.tags = vec![
Tag {
name: "Dogs".to_string(),
description: Some("Images of dogs".to_string()),
external_docs: None,
},
Tag {
name: "Cats".to_string(),
description: Some("Images of cats".to_string()),
external_docs: None,
},
Tag {
name: "Cars".to_string(), …
```

Actix operation macros to support tags and info

---

macros/src/actix.rs
tests/test_app.rs

This PR, for the example [here](https://github.com/wafflespeanut/paperclip/blob/master/book/actix-plugin.md), instead of creating a yaml like:
```
swagger: '2.0'
definitions:
Pet:
properties:
id:
type: integer
format: int64
name:
type: string
required:
- name
paths:
/pets:
post:
responses:
'200':
description: OK
schema:
$ref: '#/definitions/Pet'
parameters:
- in: body
name: body
required: true
schema:
$ref: '#/definitions/Pet'
info:
version: ''
title: ''
```
will create this, note the "type: object" after the "Pet" definition:
```
swagger: '2.0'
definitions:
Pet:
type: object
properties:
id:
type: integer
format: int64
name:
type: string
required:
- name
paths:
/pets:
post:
responses:
'200':
description: OK
schema:
$ref: '#/definitions/Pet'
parameters:
- in: body
name: body
required: true …
```

Type "object" is missing in "definitions"

---

macros/src/actix.rs
tests/test_app.rs

Currently when there are generics in the where caluse like below:
```rust
async fn get_pet_by_type<S>(_path: web::Path<S>) -> Result<web::Json<Vec<Pet>>, ()>
where
S: paperclip::v2::schema::Apiv2Schema + ToString,
{
Ok(web::Json(vec![Pet::default()]))
}
```
it will compile with exception:
```shell
error[E0599]: no function or associated item named `update_parameter` found for struct `actix_web::types::path::Path<S>` in the current scope
--> tests/test_app.rs:1559:5
|
1559 |     #[api_v2_operation]
|     ^^^^^^^^^^^^^^^^^^^ function or associated item not found in `actix_web::types::path::Path<S>`
|
::: /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.0.2/src/types/path.rs:64:1
|
64   | pub struct Path<T>(pub T);
| -------------------------- doesn't satisfy `_: …
```

Make api_v2_operation to respect where clause of function

---

core/src/v2/schema.rs
src/build/build.rs

Add the last of `chrono`s dat and time types.
The spec doesn't have a format for time so this is just an unformated string type.

Add NaiveTime type for actix plugin

---

macros/src/actix.rs

Hello!
This small change adds "\n" at the end of every line in description gathered from docstring. This allows to display markdown when using swagger.
Whereas this works perfectly for me, I'm not sure about other use-cases. For example if in future paperclip will support YAML format then this could potentially break something.
If you have any advice let me know and I'll try to amend this.

Preserve newlines in docstring description

---

CHANGELOG.md
core/src/v2/schema.rs
macros/src/actix.rs
tests/test_app.rs

Fix optional type aliases

---

macros/src/actix.rs

If someone uses `clippy::field_reassign_with_default` flag in clippy, he gets
```warning: field assignment outside of initializer for an instance created with Default::default()```
for every `Apiv2Schema` and `api_v2_operation` in his code.
This little amendment makes clippy not complain.

Fix clippy::field_reassign_with_default in macros

---

Cargo.toml
core/Cargo.toml
core/src/v2/actix.rs
core/src/v2/schema.rs

Commit adds support for [actix-files](https://crates.io/crates/actix-files).  My API needed `NamedFile` for file download endpoints.
Btw, I noticed a [failed rustfmt build](https://travis-ci.com/github/eisberg-labs/paperclip/jobs/461684094) but on existing files on master.

Support actix-files 

---

core/src/v2/actix.rs
plugins/actix-web/src/lib.rs
plugins/actix-web/src/web.rs
tests/test_app.rs

Fixes #239.
For paramters with sequences this change also adds the .items parameter of the ParameterObject and is generated recursively.
In #242 I also tried to correctly document `serde_qs::QsQuery`, but I now don't think it is possible to correctly document `serde_qs` sequences in openapi v2 and am closing that PR.

Define list items on query parameters

---

src/bin/main.rs
src/build/manifest.hbs
src/v2/codegen/mod.rs
src/v2/codegen/state.rs
tests/snapshots/test_codegen__tests__test_pet__no_root__Cargo.toml.snap
tests/test_codegen.rs

This omits the workspace definition, allowing it to be embedded in other
repositories.
hope this patch is welcome. seems to be doing what i need locally, but I may have missed something.
Signed-off-by: Erik Hollensbe <github@hollensbe.org>

Provide the --no-root flag to the CLI which allows the crate to be embedded

---

CHANGELOG.md
core/src/v2/actix.rs
macros/src/actix.rs
plugins/actix-web/src/lib.rs
plugins/actix-web/src/web.rs
tests/test_app.rs

Add missing schema to unnamed structs with >1 element.
Fix issue with unnamed structs of 1 element caused by:
6429ef4
Fix usage of structs with Path with tuples: Path<(A,B,C)>
Unnamed struct element now get named starting from 0,1..... so that we
can keep the list of properties, though they should not really be used
anywhere else than a Path.

fix(tuples): make doc work in tuple struct path

---

macros/src/actix.rs
tests/test_app.rs

Add missing documentation to struct definitions.
Updated tests.
Resolves  #290

fix(doc): missing documentation on types

---

CHANGELOG.md
macros/src/actix.rs
macros/src/lib.rs
plugins/actix-web/src/lib.rs
plugins/actix-web/src/web.rs
src/lib.rs
tests/test_app.rs

Add macro helpers for routing methods get, put, post, delete:
these are based on the actix_web macros and intended to be facilitate
use paperclip on actix_web code which already makes use of the original
macros from actix_web:
https://docs.rs/actix-web-macros/0.1.0/actix_web_macros/

feat(macro): add macro helpers for method routing

---

tests/test_app.rs

PR#297 brought the "higher-level" descriptions to the spec which meant
that PR#298 got "out of date" and so we need to fix the test.

fix(tests): PR#289 needs an update after PR#297

---

CHANGELOG.md
core/src/v2/actix.rs
core/src/v2/schema.rs
macros/src/actix.rs
macros/src/lib.rs
plugins/actix-web/src/lib.rs
src/lib.rs
tests/test_app.rs

Ability to specify an error type schema to an error response, either to
each specific error code or a common for all.
Add error overlay over an existing Apiv2Error which allows us to filter
out errors from the existing type which may not suit a particular
URI handler.
Closes #306

feat(error responses): error responses definitions

---

plugins/actix-web/src/lib.rs

I noticed there was a lot of panics in my console when accessing the swagger-ui page and I tracked it down to the contents_utf8() call in the actix-web plugin.
I replaced it with a single contents() so it should work for any file type and not just text.
I also added an expect call with a message instead of just using unwrap()

Fix favicons for swagger-ui and add simple error handling

---

plugins/actix-web/src/lib.rs

Adding must_use could be a breaking change - in these cases it probably wouldn't be
since these are functions that return a Self, but let's avoid that for now.

fix(clippy): disable must_use on the actix_web plugin

---

core/src/v2/actix.rs

Hi there,
This PR adds more tuple sizes (8 more), to support more tuple sizes.
Quite simple, I ran into the limit of 5, and expect to be using a bit more soon too :)
This PR does not affect backwards compatibility
Thanks.

Added more tuple sizes for web::Path for OperationModifier impl

---

macros/src/actix.rs
tests/test_app.rs

Hello! 
I designed a fix for #357 which is a little different from the approach in #358. This time, I'm adding the explicit rename using `#[openapi(rename = "...")]`. If there's a good way to test my approach using existing paperclip tests, I'd love to know about it.

add #[openapi(rename = "...")] attribute

---

core/src/v2/mod.rs
core/src/v2/models.rs
core/src/v3/openapi.rs
tests/test_app.rs

as a follow up to #387 which added extensions to the Info object, this PR adds extensions to the root of the OpenAPI document.

fix: add extensions to root level of spec

---

shell.nix

Update to "2022-02-22" by default.
Oxalica version is now also configurable.
Example if you want to go latest on all:
`nix-shell --run zsh --argstr date latest --argstr oxalica master`

chore(nix): update rust toolchain date

---

plugins/actix-web/src/web.rs

Hi,
I don't know if it's something you want to do but it appears that `app_data` is not exposed anymore on `paperclip_actix::web::ServiceConfig` when using actix4.

Re-expose app_data on ServiceConfig

---

.github/workflows/cicd.yml
Cargo.toml
Makefile
core/Cargo.toml
core/src/v2/actix.rs
tests/test_app.rs

Hi,
I would like to bring [validator](https://docs.rs/validator/latest/validator/) support to paperclip.
To do so I use [actix-web-validator](https://github.com/rambler-digital-solutions/actix-web-validator) as a dependency.
I did add this feature for both actix3 and actix4. I personally use it for month now in the company I'm working for.

Feat - actix web validator support

---

macros/src/actix.rs
tests/test_app.rs

Solves #407 
When using proc macros to declare the path to a route, e.g:
```rs
#[post("foo")]
async fn foo() {}
```
No `/` is prefixed to the path `foo`. It is recommended by the Actix documentation to include the `/` in the path (i.e. `/foo`), but it is not a requirment and things will work just fine without it. However, to my knowledge it does need to be present in the OpenAPI documentation. This PR addresses this issue.
I've altered the proc macro which is invoked here. It now checks if the provided path starts with a `/`, if not it will add it.
Backwards compatibility will not be broken. Specs might change, if users were using 'unprefixed' paths, those paths will now be prefixed
I've added a test in `tests/test_app.rs`: `test_simple_app`, this passes.
Thanks!

Fixed #407

---

core/src/v2/schema.rs
tests/test_app.rs

Hi,
Using the latest paperclip release (v0.7.0) I encountered a validation error with schema references.
When using the openapi json in test_app on editor.swagger.io, these kind of messages appears:
_Semantic error at paths./cats.post.parameters.0.schema.$ref
$ref values must be RFC3986-compliant percent-encoded URIs
[Jump to line 59]()_

Fix $ref URIs to be RFC3986-compliant

---

macros/src/actix.rs
tests/test_app.rs

Hi,
When using serde flatten I expect the required fields to match the one described in the definition properties.
This should fix the current behaviour by extending sub struct when flatten is used instead of inserting the current field name for the required fields.

Fix serde flatten

---

plugins/actix-web/src/web.rs
plugins/actix-web/src/web3.rs
tests/test_app.rs

When the user does not prefix nor suffix path with a slash, the documentation should build a valid path.
This PR aims to add missing slashes in all part of the url

Fix missing slash

---

CHANGELOG.md
core/src/v3/schema.rs
macros/src/actix.rs
macros/src/core.rs
tests/test_app.rs

Add example for schema and fields through openapi attribute. 
This produce valid openapi specification. I changed the example type from `String` to `serde_json::Value` because the specification describe example as 
> A free-form property to include an example of an instance for this schema.
and examples show a json like example value.
This is link to #417

Feat: add example to schema definition

---

CHANGELOG.md
macros/src/actix.rs
tests/test_app.rs

This PR add ability to mark an operation as deprecated.
To do so, either put a `deprecated` attribute to `api_v2_operation` or use the standard `deprecated` macro.

Add support for deprecated operations

---

core/src/v2/models.rs
core/tests/test_model.rs

Avoid including regex from the path template in the name
Fixes: #427

Clean name from template.

---

core/Cargo.toml

With chrono set to require only "0", a project of mine resolved chrono to 0.3 causing things to fail. It is already specified as 0.4 as a dev dependency, so I assume that is what is really intended.

Require chrono 0.4

---

macros/src/actix.rs
tests/test_app.rs

A new version of my previous non working PR, this seems to actually do what I intended.
When you have a struct with a member using a reserved word as a name, it will be specified as r#type. For Query structs, this is probably quite common. Previously they got hte name "r#type" in the openapi spec, so I just added a strip_prefix r# to handle this case.

Handle parameters on the format r#type

---

Cargo.toml

semver 1.0 is a much leaner, better crate than it was prior to 1.0. Now
it is stable and will unlikely to see further changes.
We use semver privatly, so this bump is not a semver change for us.

upgrade semver

---

macros/src/actix.rs
src/v2/mod.rs

This should close #433 or at least improve it as much as feasibly possible for existing methods.

433 support leading whitesapce

---

book/actix-plugin.md

Add documentation to add description on a single property in order to obtain the following behaviour :

feat(doc): Add doc about single property description

---

core/src/v3/openapi.rs

`schemes` and `host` settings used to be completely ignored. This PR properly handles those when populating v3 `servers` field.

feat: Respect `host` setting of v2 spec when converting to v3

---

core/src/v3/openapi.rs

The v2.extensions should be converted to root level extensions in v3 specs, not extensions in the components struct.

Move root level extensions to root

---

core/src/v2/schema.rs

Apiv2Header is currently pointing to [derive.Apiv2Security.html](https://paperclip-rs.github.io/paperclip/paperclip_actix/derive.Apiv2Security.html). I changed it so that it points to [derive.Apiv2Header.html](https://paperclip-rs.github.io/paperclip/paperclip_actix/derive.Apiv2Header.html)

fix Apiv2Header link in documentation

---

LICENSE-APACHE
LICENSE-MIT

Addresses issue #390 
Updates the name of the copyright holder in each of the licenses to "Paperclip Contributors"
I wasn't sure if we wanted to change the dates to match? Or if there was a reason the dates on the two licenses were different, so I left that the same. Please let me know if there are any other changes that should be made. This is my first time contributing to this project, so please also let me know if there are any conventions I should have followed that I didn't.  :)

Update copyrights to use "Paperclip Contributors"

---

CHANGELOG.md
Cargo.toml
book/build-script.md
core/Cargo.toml
core/src/v2/models.rs
core/src/v2/resolver.rs
core/src/v2/schema.rs
plugins/actix-web/Cargo.toml
plugins/actix-web/src/app.rs
plugins/actix-web/src/app3.rs
src/build/client_mod.hbs
src/build/manifest.hbs
src/v2/codegen/emitter.rs
tests/snapshots/test_codegen__tests__test_k8s__cli__Cargo.toml.snap
tests/snapshots/test_codegen__tests__test_k8s__cli__main.rs.snap
tests/snapshots/test_codegen__tests__test_k8s__mod.rs.snap
tests/snapshots/test_codegen__tests__test_pet__Cargo.toml.snap
tests/snapshots/test_codegen__tests__test_pet__lib.rs.snap
tests/snapshots/test_codegen__tests__test_pet__no_root__Cargo.toml.snap
tests/test_app.rs
tests/test_codegen.rs
tests/test_k8s/Cargo.toml

As pointed out in #438 the mutex performance between parking_lot should not adversely affect paperclip.
Also remove the mutexes altogether from the ApiError.
Unfortunately this is indeed a breaking change!
Resolves: #438

refactor!: switch from parking_lot to std::sync

---

.github/workflows/linter.yml

I think stable now pulls in later rust version which leads into this. We should probably consider setting MSRV as AFAIK we don't.

ci: skip clippy::derivable-impls linter for now

---

core/src/v2/actix.rs
core/src/v2/models.rs
tests/test_app.rs

There's a routine which patches parameter names and it trashes previous attempts when it runs twice.
I'm not sure this is meant to work but it seems that the only time we need this function is when we don't have param names, example:
_p: web::Path<(bool, u32, String)>
We seem to completely ignore param names and just name things from the path, example:
get(ace: web::Path<bool>, user_id: web::Path<u32>, friend: web::Path<String>) This can actually be written as
get(user_id: web::Path<bool>, ace: web::Path<u32>, friend: web::Path<String>)
Which actually swaps parameters in the generate json!!
Resolves: #501

fix(path-order): don't trash previous parameter names

---

.github/workflows/cicd.yml
CHANGELOG.md
Cargo.toml
core/Cargo.toml
plugins/actix-web/Cargo.toml
plugins/actix-web/src/app.rs
plugins/actix-web/src/app3.rs
plugins/actix-web/src/lib.rs
plugins/actix-web/src/web.rs
plugins/actix-web/src/web3.rs
src/v2/codegen/emitter.rs

Latest openapiv3 became "too flexible" for indexmap dep: ">=1.6.1, <3.0.0"
This causes issues with paperclip because we use 1.0. Upgrade to indexmap v2
Resolves #507

fix(openapiv3-indexmap): support indexmap 2

---

macros/src/actix.rs

Code generated from the `api_v2_operation` proc macro includes a unit struct definition of the form `paperclip_snake_case_struct_name` and was trigging the non-camel-case type name lint. Added the same lint ignores here as are used on the other struct definition in the same macro.

add lint ignores to paperclip unit struct

---

macros/src/actix.rs
tests/test_app.rs

This allows adding maximum an minimum as attributes to a field, example:
```rust
#[openapi(maximum = 2.0)]
age: u8
```
The max and min must be either string, float or int. They are then converted to the openapi f32 format.
Resolves: #515

feat(openapi): add max and min attribute parsing

---

core/src/v2/schema.rs

just reduces a bit of code and macro codegen
from `cargo-msrv`
master: `Finished The MSRV is: 1.65.0  `
After: `Finished The MSRV is: 1.65.0 `

switch to const generic array instead of 0-32 manual impl of schema type

---

core/src/v3/schema.rs
tests/test_app.rs

Maps were previously appearing as `fieldname: object` with no schema definitions added for the value types in the map. This PR adds the map value type as an additional property on the relevant V3 schema for the parent struct field.

fix maps in v2->v3 schema conversion

---

macros/src/actix.rs
tests/test_app.rs

Array field types were not being parsed.
Also in this case errors were not being handled gracefully.
Resolves #454

fix(actix): support parsing arrays for schemas

---

Makefile
README.md

Solves:
https://github.com/paperclip-rs/paperclip/issues/534

doc: Add instructions for git submodules

---

core/src/v2/mod.rs
macros/src/actix.rs
macros/src/core.rs
src/v2/mod.rs

Use re-export of serde_json in macros

---

CHANGELOG.md
Cargo.toml
core/Cargo.toml
macros/Cargo.toml
plugins/actix-web/Cargo.toml

This is to address min/max being added and breaking back compat. paperclip-macros 0.6.4 and 0.6.5 will be yanked from crates. paperclip 0.9.0 and 0.9.1 will also be yanked from crates.
Resolves #542

fix: bump paperclip-macros minor

---

Cargo.toml
core/Cargo.toml
core/src/v3/operation.rs
core/src/v3/parameter.rs
core/src/v3/schema.rs
core/src/v3/security_scheme.rs
plugins/actix-web/Cargo.toml

There's a breaking change on the crate which does not expose the fields as pub and so we need to use our own patch for now.

build: update openapiv3 to v2.0

---

core/Cargo.toml

We can support jiff 02 with no code changes, so this patch only loosen up the version requirements

Support jiff 0.2
